-- MySQL Script generated by MySQL Workbench
-- lun 11 oct 2021 13:31:42
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema forumEval
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema forumEval
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `forumEval` ;
USE `forumEval` ;

-- -----------------------------------------------------
-- Table `forumEval`.`role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `forumEval`.`role` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `forumEval`.`followUser`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `forumEval`.`followUser` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(80) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `forumEval`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `forumEval`.`user` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `pseudo` VARCHAR(100) NOT NULL,
  `mail` VARCHAR(100) NOT NULL,
  `password` VARCHAR(100) NOT NULL,
  `role-fk` INT UNSIGNED NOT NULL,
  `user_online_fk` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `mail_UNIQUE` (`mail` ASC) VISIBLE,
  INDEX `role-fk_idx` (`role-fk` ASC) VISIBLE,
  INDEX `user_online_fk_idx` (`user_online_fk` ASC) VISIBLE,
  CONSTRAINT `role-fk`
    FOREIGN KEY (`role-fk`)
    REFERENCES `forumEval`.`role` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `user_online_fk`
    FOREIGN KEY (`user_online_fk`)
    REFERENCES `forumEval`.`followUser` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `forumEval`.`comment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `forumEval`.`comment` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_fk` INT UNSIGNED NOT NULL,
  `subject` VARCHAR(60) NOT NULL,
  `content` TEXT NOT NULL,
  `datePost` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `user-fk_idx` (`user_fk` ASC) VISIBLE,
  CONSTRAINT `user-fk`
    FOREIGN KEY (`user_fk`)
    REFERENCES `forumEval`.`user` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `forumEval`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `forumEval`.`category` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(80) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `forumEval`.`followStatut`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `forumEval`.`categoryStatut` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(80) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `forumEval`.`subject`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `forumEval`.`subject` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(60) NOT NULL,
  `content` TEXT NOT NULL,
  `category-fk` INT UNSIGNED NOT NULL,
  `author-fk` INT UNSIGNED NOT NULL,
  `comment_fk` INT UNSIGNED NOT NULL,
  `subject_status_fk` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `category-fk_idx` (`category-fk` ASC) VISIBLE,
  INDEX `author-fk_idx` (`author-fk` ASC) VISIBLE,
  INDEX `comment_fk_idx` (`comment_fk` ASC) VISIBLE,
  INDEX `subjectStatus_fk_idx` (`subject_status_fk` ASC) VISIBLE,
  CONSTRAINT `category-fk`
    FOREIGN KEY (`category-fk`)
    REFERENCES `forumEval`.`category` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `author-fk`
    FOREIGN KEY (`author-fk`)
    REFERENCES `forumEval`.`user` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `comment_fk`
    FOREIGN KEY (`comment_fk`)
    REFERENCES `forumEval`.`comment` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `subjectStatus_fk`
    FOREIGN KEY (`subject_status_fk`)
    REFERENCES `forumEval`.`followStatut` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
